[features]
seeds = false
skip-lint = false

[programs.devnet]
myepicproject = "32Yu1ovezPREKDrdCNBEMuKGz3TXD5Ss79FNdA6T6BU4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/carmen41511/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"

[test]
startup_wait = 100000
